# This is a basic workflow to help you get started with Actions

name: CI-release

# Triggers the workflow on GitHub release
on:
  release:
    types: [ created ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        path: .gradle
        key: gradle

    # Runs a single command using the runners shell
    - name: Build project
      run: ./gradlew clean build

    - name: Publish artifacts
      run: ./gradlew -Pgpr.user=pmiklos -Pgpr.key=${{ secrets.GITHUB_TOKEN }} publish
